### ISSUE TITLE
DNS entry not replicated everywhere

### ISSUE THREAD

**Issue by larister** [chrisboakes/brighton-quarantine-delivery#2]
Fantastic website @chrisboakes! Really impressed; great to see it in Svelte.js as well. If you ever want to talk about it at https://asyncjs.com/ when this is all over I'd be super keen to hear your experience with it.

Anyway, onto the issue - I shared this with my colleagues at Brandwatch and one mentioned they couldn't access the site - they said it looks like the DNS hasn't replicated everywhere yet:

```
 dig @8.8.8.8 www.brightonquarantine.co.uk +short
157.230.103.136

dig @9.9.9.9 www.brightonquarantine.co.uk +short

... 
nada 
```

Not sure if there's anything you can do about that, have asked our network engineer but just thought I'd let you know :)

**Comment by larister** [comment]
Our network engineer suggests contacting the domain registry

**Comment by chrisboakes** [comment]
Hey @larister , thanks! I was actually at the last Serverless async before the lockdown happened - a great meetup and really well organised. For sure, happy to give a lightning talk or something absolutely 👍 

I moved the hosting at the weekend and changed over the nameservers on Sunday afternoon so it _might_ still be propagating as it hasn't been a full 48 hours yet. I'll keep an eye on it though and get it resolved!

**Comment by larister** [comment]
Hey @chrisboakes, fantastic! I'll be in touch as soon as we know when the next meeting will be happening :) 

Oh ok that's good to know, yes I think it can take a while. Our network chap says to ask here if not: https://www.quad9.net/contact/

**Comment by chrisboakes** [comment]
Hey @larister, thanks! Looking forward to attending Async again when this lockdown is over.

I've checked the DNS this morning and it's resolving:

```
dig @8.8.8.8 www.brightonquarantine.co.uk +short
142.93.108.123
dig @9.9.9.9 www.brightonquarantine.co.uk +short
167.99.137.12
```

Thanks again for the heads up!

**Comment by larister** [comment]
Great, thanks @chrisboakes!
